CUDA_VISIBLE_DEVICES=0, python main_test.py \
--n_gpu 1 \
--image_dir /data/MIMIC-CXR/images/ \
--ann_path /data/MIMIC-CXR/mimic_annotation_promptmrg.json \
--dataset_name mimic_cxr \
--gen_max_len 150 \
--gen_min_len 100 \
--batch_size 16 \
--save_dir results/ClinAlign_mimic_cxr \
--seed 456789 \
--clip_k 16 \
--beam_size 1 \
--load_pretrained results/ClinAlign_mimic_cxr/model_best_epoch.pth
